/**
 * autogendForms.js
 *
 * Form component builders for individual field types in Autogen Data settings:
 *  - System / Pre-configured fields (id, tokenKey, primaryKey)
 *  - Date / Timestamp fields (created, updated, autodate, date fields)
 *    -> Supports "Time of Generation Action" vs "Date / Time Ranges"
 *  - File fields -> Extensions + sample file uploads (Max 5 files <= 500KB)
 *  - Select fields -> Dropdown choices with option deduplication
 *  - Bool fields -> Fixed 2 options (true / false)
 *  - Text fields -> Autogenerate Pattern input
 *  - Number fields -> Min & Max Range inputs + Integer vs Float mode selector
 *  - Email & Password fields
 */

/**
 * Renders a locked, read-only field card for pre-configured autogenerated fields
 */
export function renderSystemFieldCard(field) {
    const patternHint = field.autogeneratePattern
        ? `Pattern: "${field.autogeneratePattern}"`
        : "Autogenerated on record creation";

    return t.div(
        { className: "field-card-spacious disabled-card" },
        t.div(
            { className: "field-card-header" },
            t.div(
                { className: "flex align-center gap-10" },
                t.strong({ className: "txt-lg" }, field.name),
                t.span({ className: "label label-sm secondary" }, field.type),
                t.span({ className: "label label-sm info" }, "Auto Generated"),
            ),
        ),
        t.div(
            { className: "p-10 background-subtle radius txt-hint txt-sm flex align-center justify-between" },
            t.div(
                { className: "flex align-center gap-5" },
                t.i({ className: "ri-lock-line" }),
                t.span({}, `Field "${field.name}" is automatically generated upon record creation.`),
            ),
            t.code({ className: "txt-xs" }, patternHint),
        ),
    );
}

/**
 * Renders Date / Timestamp fields (created, updated, autodate, date)
 */
export function renderDateFieldCard(field, conf, handlers, uniqueId) {
    const isActionTime = conf.dateMode === "action_time" || !conf.dateMode;
    const isSystem = field.system || field.type === "autodate" || field.name === "created" || field.name === "updated";

    return t.div(
        { className: "field-card-spacious" },

        // Header
        t.div(
            { className: "field-card-header" },
            t.div(
                { className: "flex align-center gap-10" },
                t.strong({ className: "txt-lg" }, field.name),
                t.span({ className: "label label-sm secondary" }, field.type),
                isSystem ? t.span({ className: "label label-sm info" }, "System Timestamp") : null,
            ),
        ),

        // Date Generation Mode Switcher
        t.div(
            { className: "flex align-center gap-20 m-b-md" },
            t.span({ className: "txt-hint txt-sm txt-bold" }, "Timestamp Mode:"),
            t.div(
                { className: "field-radio-native" },
                t.input({
                    id: `${uniqueId}_date_act_${field.id}`,
                    type: "radio",
                    name: `date_mode_${field.id}`,
                    checked: () => isActionTime,
                    onchange: () => handlers.toggleDateMode(field.id, "action_time"),
                }),
                t.label({ htmlFor: `${uniqueId}_date_act_${field.id}` }, "Time of Action (Current Execution Time)"),
            ),
            t.div(
                { className: "field-radio-native" },
                t.input({
                    id: `${uniqueId}_date_rng_${field.id}`,
                    type: "radio",
                    name: `date_mode_${field.id}`,
                    checked: () => !isActionTime,
                    onchange: () => handlers.toggleDateMode(field.id, "range"),
                }),
                t.label({ htmlFor: `${uniqueId}_date_rng_${field.id}` }, "Date / Time Ranges (From - To)"),
            ),
        ),

        // MODE 1: Time of Action Banner
        () => {
            if (!isActionTime) return null;

            return t.div(
                { className: "p-12 background-subtle radius txt-hint txt-sm flex align-center gap-10" },
                t.i({ className: "ri-time-line txt-lg" }),
                t.span({}, `Every record created will be timestamped with the exact time of the generation execution.`),
            );
        },

        // MODE 2: Date / Time Ranges controls
        () => {
            if (isActionTime) return null;

            return t.div(
                { className: "date-range-mode-wrapper" },

                // Distribution Mode
                t.div(
                    { className: "flex align-center gap-20 m-b-sm" },
                    t.span({ className: "txt-hint txt-sm txt-bold" }, "Distribution:"),
                    t.div(
                        { className: "field-radio-native" },
                        t.input({
                            id: `${uniqueId}_dist_eq_${field.id}`,
                            type: "radio",
                            name: `dist_${field.id}`,
                            checked: () => conf.distribution === "equal",
                            onchange: () => handlers.toggleDistribution(field.id, "equal"),
                        }),
                        t.label({ htmlFor: `${uniqueId}_dist_eq_${field.id}` }, "Equal Split"),
                    ),
                    t.div(
                        { className: "field-radio-native" },
                        t.input({
                            id: `${uniqueId}_dist_man_${field.id}`,
                            type: "radio",
                            name: `dist_${field.id}`,
                            checked: () => conf.distribution === "manual",
                            onchange: () => handlers.toggleDistribution(field.id, "manual"),
                        }),
                        t.label({ htmlFor: `${uniqueId}_dist_man_${field.id}` }, "Weighted / Manual"),
                    ),
                ),

                // Variations List (From - To Date Pairs)
                t.div(
                    { className: "variations-list-spacious" },
                    () => (conf.dateRanges || []).map((range, idx) => {
                        return t.div(
                            { className: "variation-row-spacious align-center" },
                            t.div(
                                { className: "field m-b-0 flex-1" },
                                t.label({ className: "txt-bold txt-xs m-b-xs" }, "From Date"),
                                t.input({
                                    type: "datetime-local",
                                    className: "input",
                                    value: () => range.from,
                                    onchange: (e) => handlers.updateDateRangePair(field.id, idx, e.target.value, range.to, range.weight),
                                }),
                            ),
                            t.div(
                                { className: "field m-b-0 flex-1" },
                                t.label({ className: "txt-bold txt-xs m-b-xs" }, "To Date"),
                                t.input({
                                    type: "datetime-local",
                                    className: "input",
                                    value: () => range.to,
                                    onchange: (e) => handlers.updateDateRangePair(field.id, idx, range.from, e.target.value, range.weight),
                                }),
                            ),
                            conf.distribution === "manual" ? t.div(
                                { className: "field addon m-b-0" },
                                t.label({ className: "txt-bold txt-xs m-b-xs" }, "Weight"),
                                t.div(
                                    { className: "flex align-center" },
                                    t.input({
                                        type: "number",
                                        className: "input w-90",
                                        min: 0,
                                        max: 100,
                                        value: () => range.weight,
                                        onchange: (e) => handlers.updateDateRangePair(field.id, idx, range.from, range.to, e.target.value),
                                    }),
                                    t.span({ className: "txt-hint txt-xs m-l-5" }, "%"),
                                ),
                            ) : null,
                            t.button(
                                {
                                    type: "button",
                                    className: "btn btn-circle transparent danger m-t-md",
                                    disabled: () => conf.dateRanges.length <= 1,
                                    onclick: () => handlers.removeDateRangePair(field.id, idx),
                                },
                                t.i({ className: "ri-delete-bin-line" }),
                            ),
                        );
                    }),
                ),

                t.button(
                    {
                        type: "button",
                        className: "btn secondary transparent m-t-sm",
                        onclick: () => handlers.addDateRangePair(field.id),
                    },
                    t.i({ className: "ri-add-line" }),
                    t.span({ className: "txt" }, "Add Date Range (From - To)"),
                ),
            );
        },
    );
}

/**
 * Renders Text/String fields with automatic default pattern `Sample fieldName [1-100]`
 */
export function renderTextFieldCard(field, conf, handlers, uniqueId) {
    const defaultPattern = `Sample ${field.name} [1-100]`;
    const currentVal = conf.pattern !== undefined && conf.pattern !== "" ? conf.pattern : defaultPattern;

    return t.div(
        { className: "field-card-spacious" },

        // Header
        t.div(
            { className: "field-card-header" },
            t.div(
                { className: "flex align-center gap-10" },
                t.strong({ className: "txt-lg" }, field.name),
                t.span({ className: "label label-sm secondary" }, field.type),
                field.required ? t.span({ className: "label label-sm danger" }, "Required") : null,
                field.pattern ? t.span({ className: "label label-sm info" }, `Validation: ${field.pattern}`) : null,
            ),
            t.div(
                { className: "field-toggle-native" },
                t.input({
                    id: `${uniqueId}_salt_${field.id}`,
                    type: "checkbox",
                    checked: () => conf.uniqueSalt,
                    onchange: (e) => handlers.toggleUniqueSalt(field.id, e.target.checked),
                }),
                t.label({ htmlFor: `${uniqueId}_salt_${field.id}` }, "Unique Salt (UUID)"),
            ),
        ),

        // Default Value / Pattern / Value Input
        t.div(
            { className: "pattern-mode-wrapper" },
            t.div(
                { className: "flex gap-15 m-b-xs" },
                t.div(
                    { className: "field m-b-0 flex-1" },
                    t.label({ className: "txt-bold" }, "Constant Default Value"),
                    t.input({
                        type: "text",
                        className: "input",
                        placeholder: "e.g. Acme Corp (Applies same value to all rows)",
                        value: () => conf.defaultValue || "",
                        onchange: (e) => handlers.updateDefaultValue(field.id, e.target.value),
                    }),
                ),
                t.div(
                    { className: "field m-b-0 flex-1" },
                    t.label({ className: "txt-bold" }, "Autogenerate Pattern (Regex / Value)"),
                    t.input({
                        type: "text",
                        className: "input",
                        placeholder: `e.g. ${defaultPattern}`,
                        value: () => currentVal,
                        onchange: (e) => handlers.updateFieldPattern(field.id, e.target.value),
                    }),
                ),
            ),
            t.div(
                { className: "field-help" },
                "Generates unique or combined values for all records. ",
                t.br(),
                "Examples: ",
                t.code({}, "[Alex|Jordan|Emma|Sam] [Smith|Brown|Jones]"),
                " (combinations), ",
                t.code({}, `Sample ${field.name} [1-100]`),
                ", or static text like ",
                t.code({}, "ismail"),
            ),
        ),
    );
}

/**
 * Renders Bool field card - fixed 2 options (true / false) without any "+" add button
 */
export function renderBoolFieldCard(field, conf, handlers, uniqueId) {
    const boolOptions = ["true", "false"];

    return t.div(
        { className: "field-card-spacious" },

        // Header
        t.div(
            { className: "field-card-header" },
            t.div(
                { className: "flex align-center gap-10" },
                t.strong({ className: "txt-lg" }, field.name),
                t.span({ className: "label label-sm secondary" }, field.type),
                field.required ? t.span({ className: "label label-sm danger" }, "Required") : null,
            ),
        ),

        // Distribution Mode
        t.div(
            { className: "flex align-center gap-20 m-b-sm" },
            t.span({ className: "txt-hint txt-sm txt-bold" }, "Distribution:"),
            t.div(
                { className: "field-radio-native" },
                t.input({
                    id: `${uniqueId}_dist_eq_${field.id}`,
                    type: "radio",
                    name: `dist_${field.id}`,
                    checked: () => conf.distribution === "equal",
                    onchange: () => handlers.toggleDistribution(field.id, "equal"),
                }),
                t.label({ htmlFor: `${uniqueId}_dist_eq_${field.id}` }, "Equal Split"),
            ),
            t.div(
                { className: "field-radio-native" },
                t.input({
                    id: `${uniqueId}_dist_man_${field.id}`,
                    type: "radio",
                    name: `dist_${field.id}`,
                    checked: () => conf.distribution === "manual",
                    onchange: () => handlers.toggleDistribution(field.id, "manual"),
                }),
                t.label({ htmlFor: `${uniqueId}_dist_man_${field.id}` }, "Weighted / Manual"),
            ),
        ),

        // Variations List (Fixed 2: true / false)
        t.div(
            { className: "variations-list-spacious" },
            () => conf.variations.slice(0, 2).map((v, idx) => {
                return t.div(
                    { className: "variation-row-spacious" },
                    t.div(
                        { className: "field m-b-0 flex-1" },
                        t.select(
                            {
                                className: "select",
                                value: () => v.value,
                                onchange: (e) => handlers.updateVariationValue(field.id, idx, e.target.value),
                            },
                            boolOptions.map((opt) => t.option({ value: opt }, opt)),
                        ),
                    ),
                    conf.distribution === "manual" ? t.div(
                        { className: "field addon m-b-0" },
                        t.input({
                            type: "number",
                            className: "input w-90",
                            min: 0,
                            max: 100,
                            step: 1,
                            value: () => v.weight,
                            onchange: (e) => handlers.updateVariationWeight(field.id, idx, e.target.value),
                        }),
                        t.span({ className: "percent-icon-label txt-xs" }, "%"),
                    ) : null,
                );
            }),
        ),
    );
}

/**
 * Renders File fields with neat styling + Sample File Upload (Max 5 files, <= 500KB each)
 */
export function renderFileFieldCard(field, conf, handlers, uniqueId) {
    const samples = conf.sampleFiles || [];
    const mimeTypes = field.mimeTypes || [];
    const maxSelect = field.maxSelect || 1;

    return t.div(
        { className: "field-card-spacious" },

        // Header
        t.div(
            { className: "field-card-header" },
            t.div(
                { className: "flex align-center gap-10" },
                t.strong({ className: "txt-lg" }, field.name),
                t.span({ className: "label label-sm secondary" }, field.type),
                field.required ? t.span({ className: "label label-sm danger" }, "Required") : null,
                maxSelect > 1 ? t.span({ className: "label label-sm info" }, `Max ${maxSelect} files per record`) : null,
            ),
        ),

        // File Extension / Type Selector
        t.div(
            { className: "field flex-1 m-b-sm" },
            t.label({ className: "txt-bold" }, "Allowed File Type / Extension"),
            t.input({
                type: "text",
                className: "input",
                placeholder: "e.g. png, jpg, webp, pdf",
                value: () => {
                    const val = conf.fileExtension || (mimeTypes.length ? mimeTypes.map((m) => m.split("/")[1] || m).join(", ") : "pdf");
                    return val.replace(/image\//g, "");
                },
                onchange: (e) => handlers.updateFileExtension(field.id, e.target.value),
            }),
            t.div({ className: "field-help" }, "Specify file extensions to generate (e.g. png, jpg, webp, pdf)."),
        ),

        // Sample Files Upload List
        t.div(
            { className: "sample-files-section p-15 radius background-subtle m-t-sm" },
            t.div(
                { className: "flex align-center justify-between m-b-xs" },
                t.label({ className: "txt-bold" }, `Sample Files (${samples.length} / 5 max)`),
                t.span({ className: "txt-hint txt-xs" }, "Max size: 500KB per file"),
            ),

            // Files List
            samples.length ? t.div(
                { className: "variations-list-spacious m-b-sm" },
                () => samples.map((f, idx) => {
                    return t.div(
                        { className: "variation-row-spacious align-center" },
                        t.div(
                            { className: "flex align-center gap-10 flex-1 p-10 background-surface radius border-subtle" },
                            t.i({ className: "ri-file-text-line txt-lg" }),
                            t.div(
                                { className: "flex-1 overflow-hidden" },
                                t.div({ className: "txt-bold txt-ellipsis" }, f.name),
                                t.div({ className: "txt-hint txt-xs" }, `${(f.size / 1024).toFixed(1)} KB`),
                            ),
                        ),
                        t.button(
                            {
                                type: "button",
                                className: "btn btn-circle transparent danger",
                                onclick: () => handlers.removeSampleFile(field.id, idx),
                            },
                            t.i({ className: "ri-delete-bin-line" }),
                        ),
                    );
                }),
            ) : null,

            // Upload Sample File Button
            t.div(
                { className: "upload-file-button-wrapper m-t-xs" },
                t.input({
                    id: `${uniqueId}_file_upload_${field.id}`,
                    type: "file",
                    accept: (() => {
                        const raw = conf.fileExtension || (mimeTypes.length ? mimeTypes.join(",") : "*");
                        if (raw === "*") return "*";
                        return raw
                            .split(",")
                            .map((s) => {
                                const trimmed = s.trim();
                                if (trimmed.includes("/")) {
                                    const parts = trimmed.split("/");
                                    return "." + (parts[1] === "jpeg" ? "jpg" : parts[1]);
                                }
                                return trimmed.startsWith(".") ? trimmed : "." + trimmed;
                            })
                            .join(",");
                    })(),
                    style: "display: none;",
                    onchange: (e) => {
                        const file = e.target.files?.[0];
                        if (!file) return;

                        if (file.size > 500 * 1024) {
                            app.toasts.error(`File "${file.name}" exceeds maximum allowed limit of 500KB!`);
                            e.target.value = "";
                            return;
                        }

                        if (samples.length >= 5) {
                            app.toasts.error("Maximum 5 sample files allowed per field!");
                            e.target.value = "";
                            return;
                        }

                        handlers.addSampleFile(field.id, {
                            name: file.name,
                            size: file.size,
                            type: file.type,
                        });
                        e.target.value = "";
                    },
                }),
                t.button(
                    {
                        type: "button",
                        className: "btn secondary outline sm",
                        disabled: () => samples.length >= 5,
                        onclick: () => {
                            document.getElementById(`${uniqueId}_file_upload_${field.id}`)?.click();
                        },
                    },
                    t.i({ className: "ri-upload-cloud-line" }),
                    t.span(
                        { className: "txt" },
                        samples.length >= 5 ? "Max 5 sample files reached" : "Upload Sample File (Max 500KB)",
                    ),
                ),
            ),
        ),
    );
}

/**
 * Renders Email field card
 */
export function renderEmailFieldCard(field, conf, handlers, uniqueId) {
    const defaultPattern = "user[1-1000]@example.com";

    return t.div(
        { className: "field-card-spacious" },

        // Header
        t.div(
            { className: "field-card-header" },
            t.div(
                { className: "flex align-center gap-10" },
                t.strong({ className: "txt-lg" }, field.name),
                t.span({ className: "label label-sm secondary" }, field.type),
                field.required ? t.span({ className: "label label-sm danger" }, "Required") : null,
            ),
            t.div(
                { className: "field-toggle-native" },
                t.input({
                    id: `${uniqueId}_salt_${field.id}`,
                    type: "checkbox",
                    checked: () => conf.uniqueSalt,
                    onchange: (e) => handlers.toggleUniqueSalt(field.id, e.target.checked),
                }),
                t.label({ htmlFor: `${uniqueId}_salt_${field.id}` }, "Unique Salt (UUID)"),
            ),
        ),

        // Pattern / Email Generator Input
        t.div(
            { className: "pattern-mode-wrapper" },
            t.div(
                { className: "field m-b-xs" },
                t.label({ className: "txt-bold" }, "Autogenerate Email Pattern"),
                t.input({
                    type: "text",
                    className: "input",
                    placeholder: `e.g. ${defaultPattern}`,
                    value: () => conf.pattern !== undefined && conf.pattern !== "" ? conf.pattern : defaultPattern,
                    onchange: (e) => handlers.updateFieldPattern(field.id, e.target.value),
                }),
            ),
            t.div(
                { className: "field-help" },
                "Generates valid unique emails for records. ",
                t.br(),
                "Examples: ",
                t.code({}, "user[1-1000]@example.com"),
                ", ",
                t.code({}, "test.[a-z0-9]{8}@domain.com"),
                ", or static email like ",
                t.code({}, "user1@example.com"),
            ),
        ),
    );
}

/**
 * Renders URL field card
 */
export function renderUrlFieldCard(field, conf, handlers, uniqueId) {
    const defaultPattern = "https://example.com/user/[1-1000]";
    const currentVal = conf.pattern !== undefined && conf.pattern !== "" ? conf.pattern : defaultPattern;

    return t.div(
        { className: "field-card-spacious" },

        // Header
        t.div(
            { className: "field-card-header" },
            t.div(
                { className: "flex align-center gap-10" },
                t.strong({ className: "txt-lg" }, field.name),
                t.span({ className: "label label-sm secondary" }, field.type),
                field.required ? t.span({ className: "label label-sm danger" }, "Required") : null,
            ),
            t.div(
                { className: "field-toggle-native" },
                t.input({
                    id: `${uniqueId}_salt_${field.id}`,
                    type: "checkbox",
                    checked: () => conf.uniqueSalt,
                    onchange: (e) => handlers.toggleUniqueSalt(field.id, e.target.checked),
                }),
                t.label({ htmlFor: `${uniqueId}_salt_${field.id}` }, "Unique Salt (UUID)"),
            ),
        ),

        // Constant Default URL & Autogenerate URL Pattern Inputs
        t.div(
            { className: "pattern-mode-wrapper" },
            t.div(
                { className: "flex gap-15 m-b-xs" },
                t.div(
                    { className: "field m-b-0 flex-1" },
                    t.label({ className: "txt-bold" }, "Constant Default URL"),
                    t.input({
                        type: "url",
                        className: "input",
                        placeholder: "e.g. https://example.com",
                        value: () => conf.defaultValue || "",
                        onchange: (e) => handlers.updateDefaultValue(field.id, e.target.value),
                    }),
                ),
                t.div(
                    { className: "field m-b-0 flex-1" },
                    t.label({ className: "txt-bold" }, "Autogenerate URL Pattern"),
                    t.input({
                        type: "text",
                        className: "input",
                        placeholder: `e.g. ${defaultPattern}`,
                        value: () => currentVal,
                        onchange: (e) => handlers.updateFieldPattern(field.id, e.target.value),
                    }),
                ),
            ),
            t.div(
                { className: "field-help" },
                "Generates valid URLs for records. ",
                t.br(),
                "Examples: ",
                t.code({}, "https://example.com"),
                " (static constant), ",
                t.code({}, "https://example.com/user/[1-1000]"),
                ", or ",
                t.code({}, "https://[site1|site2|site3].com/profile"),
            ),
        ),
    );
}

/**
 * Renders Password field card
 */
export function renderPasswordFieldCard(field, conf, handlers, uniqueId) {
    const defaultPattern = conf.pattern || "1234567890";

    return t.div(
        { className: "field-card-spacious" },

        // Header
        t.div(
            { className: "field-card-header" },
            t.div(
                { className: "flex align-center gap-10" },
                t.strong({ className: "txt-lg" }, field.name),
                t.span({ className: "label label-sm secondary" }, field.type),
                t.span({ className: "label label-sm danger" }, "Required (Min 8 chars)"),
            ),
        ),

        // Password Generator Input
        t.div(
            { className: "pattern-mode-wrapper" },
            t.div(
                { className: "field m-b-xs" },
                t.label({ className: "txt-bold" }, "Password for Records (Min 8 characters)"),
                t.input({
                    type: "text",
                    className: "input",
                    placeholder: "e.g. 1234567890 or [a-zA-Z0-9]{12}",
                    value: () => conf.pattern !== undefined && conf.pattern !== "" ? conf.pattern : defaultPattern,
                    onchange: (e) => handlers.updateFieldPattern(field.id, e.target.value),
                }),
            ),
            t.div(
                { className: "field-help" },
                "All generated users will be assigned this password (minimum 8 characters). ",
                t.br(),
                "Example: ",
                t.code({}, "1234567890"),
                " or random pattern ",
                t.code({}, "[a-zA-Z0-9]{12}"),
            ),
        ),
    );
}

/**
 * Renders Number fields with Min & Max Range autogeneration controls + Integer vs Float mode selector
 */
export function renderNumberFieldCard(field, conf, handlers, uniqueId) {
    const minVal = conf.min !== undefined ? conf.min : (field.min !== null && field.min !== undefined ? field.min : 20);
    const maxVal = conf.max !== undefined ? conf.max : (field.max !== null && field.max !== undefined ? field.max : 30);
    const numberType = conf.numberType || (field.onlyInt ? "int" : "int");

    return t.div(
        { className: "field-card-spacious" },

        // Header
        t.div(
            { className: "field-card-header" },
            t.div(
                { className: "flex align-center gap-10" },
                t.strong({ className: "txt-lg" }, field.name),
                t.span({ className: "label label-sm secondary" }, field.type),
                field.required ? t.span({ className: "label label-sm danger" }, "Required") : null,
            ),
        ),

        // Number Format Switcher: Integer vs Float
        t.div(
            { className: "flex align-center gap-20 m-b-lg" },
            t.span({ className: "txt-hint txt-sm txt-bold" }, "Number Format:"),
            t.div(
                { className: "field-radio-native" },
                t.input({
                    id: `${uniqueId}_num_int_${field.id}`,
                    type: "radio",
                    name: `num_type_${field.id}`,
                    checked: () => numberType === "int",
                    onchange: () => handlers.updateNumberType(field.id, "int"),
                }),
                t.label({ htmlFor: `${uniqueId}_num_int_${field.id}` }, "Integer (Whole Numbers)"),
            ),
            t.div(
                { className: "field-radio-native" },
                t.input({
                    id: `${uniqueId}_num_flt_${field.id}`,
                    type: "radio",
                    name: `num_type_${field.id}`,
                    checked: () => numberType === "float",
                    disabled: () => !!field.onlyInt,
                    onchange: () => handlers.updateNumberType(field.id, "float"),
                }),
                t.label(
                    { htmlFor: `${uniqueId}_num_flt_${field.id}` },
                    field.onlyInt ? "Floating Point (Schema restricted to Integer)" : "Floating Point (Decimals)",
                ),
            ),
        ),

        // Number Range Inputs
        t.div(
            { className: "number-range-wrapper m-t-md" },
            t.div(
                { className: "flex align-center gap-20 m-b-xs" },
                t.div(
                    { className: "field m-b-0 w-180" },
                    t.label({ className: "txt-bold" }, "Min Value"),
                    t.input({
                        type: "number",
                        className: "input",
                        step: numberType === "float" ? "0.01" : "1",
                        placeholder: "e.g. 20",
                        value: () => minVal,
                        onchange: (e) => handlers.updateNumberRange(field.id, e.target.value, maxVal),
                    }),
                ),
                t.div(
                    { className: "field m-b-0 w-180" },
                    t.label({ className: "txt-bold" }, "Max Value"),
                    t.input({
                        type: "number",
                        className: "input",
                        step: numberType === "float" ? "0.01" : "1",
                        placeholder: "e.g. 30",
                        value: () => maxVal,
                        onchange: (e) => handlers.updateNumberRange(field.id, minVal, e.target.value),
                    }),
                ),
            ),
            t.div(
                { className: "field-help" },
                `Generates random ${numberType === "float" ? "decimal" : "whole"} numbers between `,
                t.strong({}, `${minVal}`),
                ` and `,
                t.strong({}, `${maxVal}`),
                ` across all records.`,
            ),
        ),
    );
}

/**
 * Renders Select field form with dropdown options populated directly from collection field choices.
 */
export function renderSelectFieldCard(field, conf, handlers, uniqueId) {
    const availableOptions = field.values || field.options || [];

    function getSelectedValuesExcept(currentIndex) {
        return conf.variations
            .filter((_, idx) => idx !== currentIndex)
            .map((v) => v.value);
    }

    return t.div(
        { className: "field-card-spacious" },

        // Header
        t.div(
            { className: "field-card-header" },
            t.div(
                { className: "flex align-center gap-10" },
                t.strong({ className: "txt-lg" }, field.name),
                t.span({ className: "label label-sm secondary" }, field.type),
                field.required ? t.span({ className: "label label-sm danger" }, "Required") : null,
            ),
        ),

        // Distribution Mode
        t.div(
            { className: "flex align-center gap-20 m-b-sm" },
            t.span({ className: "txt-hint txt-sm txt-bold" }, "Distribution:"),
            t.div(
                { className: "field-radio-native" },
                t.input({
                    id: `${uniqueId}_dist_eq_${field.id}`,
                    type: "radio",
                    name: `dist_${field.id}`,
                    checked: () => conf.distribution === "equal",
                    onchange: () => handlers.toggleDistribution(field.id, "equal"),
                }),
                t.label({ htmlFor: `${uniqueId}_dist_eq_${field.id}` }, "Equal Split"),
            ),
            t.div(
                { className: "field-radio-native" },
                t.input({
                    id: `${uniqueId}_dist_man_${field.id}`,
                    type: "radio",
                    name: `dist_${field.id}`,
                    checked: () => conf.distribution === "manual",
                    onchange: () => handlers.toggleDistribution(field.id, "manual"),
                }),
                t.label({ htmlFor: `${uniqueId}_dist_man_${field.id}` }, "Weighted / Manual"),
            ),
        ),

        // Variations list
        t.div(
            { className: "variations-list-spacious" },
            () => conf.variations.map((v, idx) => {
                const pickedInOthers = getSelectedValuesExcept(idx);

                return t.div(
                    { className: "variation-row-spacious" },
                    t.div(
                        { className: "field m-b-0 flex-1" },
                        t.select(
                            {
                                className: "select",
                                value: () => v.value,
                                onchange: (e) => handlers.updateVariationValue(field.id, idx, e.target.value),
                            },
                            () => {
                                const optionEls = [];
                                if (!v.value) {
                                    optionEls.push(t.option({ value: "", disabled: true, selected: true }, "-- Select Option --"));
                                }

                                for (const opt of availableOptions) {
                                    const isAlreadyPicked = pickedInOthers.includes(opt);
                                    optionEls.push(
                                        t.option(
                                            {
                                                value: opt,
                                                disabled: isAlreadyPicked,
                                            },
                                            isAlreadyPicked ? `${opt} (already selected)` : opt,
                                        ),
                                    );
                                }
                                return optionEls;
                            },
                        ),
                    ),
                    conf.distribution === "manual" ? t.div(
                        { className: "field addon m-b-0" },
                        t.input({
                            type: "number",
                            className: "input w-90",
                            min: 0,
                            max: 100,
                            step: 1,
                            value: () => v.weight,
                            onchange: (e) => handlers.updateVariationWeight(field.id, idx, e.target.value),
                        }),
                        t.span({ className: "percent-icon-label txt-xs" }, "%"),
                    ) : null,
                    t.button(
                        {
                            type: "button",
                            className: "btn btn-circle transparent danger",
                            disabled: () => conf.variations.length <= 1,
                            onclick: () => handlers.removeVariation(field.id, idx),
                        },
                        t.i({ className: "ri-delete-bin-line" }),
                    ),
                );
            }),
        ),

        t.button(
            {
                type: "button",
                className: "btn secondary transparent m-t-sm",
                disabled: () => availableOptions.length > 0 && conf.variations.length >= availableOptions.length,
                onclick: () => {
                    const currentValues = conf.variations.map((v) => v.value);
                    const nextOpt = availableOptions.find((opt) => !currentValues.includes(opt)) || "";
                    handlers.addVariation(field.id, nextOpt);
                },
            },
            t.i({ className: "ri-add-line" }),
            t.span(
                { className: "txt" },
                availableOptions.length > 0 && conf.variations.length >= availableOptions.length
                    ? "All options selected"
                    : "Add Option Variation",
            ),
        ),
    );
}

/**
 * Renders standard generic field form
 */
export function renderGenericFieldCard(field, conf, handlers, uniqueId) {
    return t.div(
        { className: "field-card-spacious" },

        // Header
        t.div(
            { className: "field-card-header" },
            t.div(
                { className: "flex align-center gap-10" },
                t.strong({ className: "txt-lg" }, field.name),
                t.span({ className: "label label-sm secondary" }, field.type),
                field.required ? t.span({ className: "label label-sm danger" }, "Required") : null,
            ),
            t.div(
                { className: "field-toggle-native" },
                t.input({
                    id: `${uniqueId}_salt_${field.id}`,
                    type: "checkbox",
                    checked: () => conf.uniqueSalt,
                    onchange: (e) => handlers.toggleUniqueSalt(field.id, e.target.checked),
                }),
                t.label({ htmlFor: `${uniqueId}_salt_${field.id}` }, "Unique Salt (UUID)"),
            ),
        ),

        // Distribution Mode
        t.div(
            { className: "flex align-center gap-20 m-b-sm" },
            t.span({ className: "txt-hint txt-sm txt-bold" }, "Distribution:"),
            t.div(
                { className: "field-radio-native" },
                t.input({
                    id: `${uniqueId}_dist_eq_${field.id}`,
                    type: "radio",
                    name: `dist_${field.id}`,
                    checked: () => conf.distribution === "equal",
                    onchange: () => handlers.toggleDistribution(field.id, "equal"),
                }),
                t.label({ htmlFor: `${uniqueId}_dist_eq_${field.id}` }, "Equal Split"),
            ),
            t.div(
                { className: "field-radio-native" },
                t.input({
                    id: `${uniqueId}_dist_man_${field.id}`,
                    type: "radio",
                    name: `dist_${field.id}`,
                    checked: () => conf.distribution === "manual",
                    onchange: () => handlers.toggleDistribution(field.id, "manual"),
                }),
                t.label({ htmlFor: `${uniqueId}_dist_man_${field.id}` }, "Weighted / Manual"),
            ),
        ),

        // Variations List
        t.div(
            { className: "variations-list-spacious" },
            () => conf.variations.map((v, idx) => {
                return t.div(
                    { className: "variation-row-spacious" },
                    t.div(
                        { className: "field m-b-0 flex-1" },
                        t.input({
                            type: "text",
                            className: "input",
                            placeholder: `Variation ${idx + 1}`,
                            value: () => v.value,
                            onchange: (e) => handlers.updateVariationValue(field.id, idx, e.target.value),
                        }),
                    ),
                    conf.distribution === "manual" ? t.div(
                        { className: "field addon m-b-0" },
                        t.input({
                            type: "number",
                            className: "input w-90",
                            min: 0,
                            max: 100,
                            step: 1,
                            value: () => v.weight,
                            onchange: (e) => handlers.updateVariationWeight(field.id, idx, e.target.value),
                        }),
                        t.span({ className: "percent-icon-label txt-xs" }, "%"),
                    ) : null,
                    t.button(
                        {
                            type: "button",
                            className: "btn btn-circle transparent danger",
                            disabled: () => conf.variations.length <= 1,
                            onclick: () => handlers.removeVariation(field.id, idx),
                        },
                        t.i({ className: "ri-delete-bin-line" }),
                    ),
                );
            }),
        ),

        t.button(
            {
                type: "button",
                className: "btn secondary transparent m-t-sm",
                onclick: () => handlers.addVariation(field.id),
            },
            t.i({ className: "ri-add-line" }),
            t.span({ className: "txt" }, "Add Variation"),
        ),
    );
}
